CREATE TABLE UpSelling
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
WithAlgorithm BIT NULL,
PriorityInAlgorithm BIT NULL,
ProductsToShow INT NULL,
CONSTRAINT PK_UpSelling_Guid PRIMARY KEY(Guid)
);

CREATE TABLE CrossSelling
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
WithAlgorithm BIT NULL,
PriorityInAlgorithm BIT NULL,
ProductsToShow INT NULL,
CONSTRAINT PK_CrossSelling_Guid PRIMARY KEY(Guid)
);

ALTER TABLE Product ADD CrossSellingGuid UNIQUEIDENTIFIER NOT NULL;
ALTER TABLE Product ADD CONSTRAINT FK_Product_CrossSellingGuid FOREIGN KEY (CrossSellingGuid) REFERENCES CrossSelling(Guid);

ALTER TABLE Product ADD UpSellingGuid UNIQUEIDENTIFIER NOT NULL;
ALTER TABLE Product ADD CONSTRAINT FK_Product_UpSellingGuid FOREIGN KEY (UpSellingGuid) REFERENCES UpSelling(Guid);

CREATE TABLE ProductUpSelling
(
UpSellingGuid UNIQUEIDENTIFIER NOT NULL,
ProductGuid UNIQUEIDENTIFIER NOT NULL,
[Order] INT NOT NULL,
CONSTRAINT FK_ProductUpSelling_UpSellingGuid FOREIGN KEY (UpSellingGuid) REFERENCES UpSelling(Guid),
CONSTRAINT FK_ProductUpSelling_ProductGuid FOREIGN KEY (ProductGuid) REFERENCES Product(Guid),
);

CREATE TABLE ProductCrossSelling
(
CrossSellingGuid UNIQUEIDENTIFIER NOT NULL,
ProductGuid UNIQUEIDENTIFIER NOT NULL,
[Order] INT NOT NULL,
CONSTRAINT FK_ProductCrossSelling_CrossSellingGuid FOREIGN KEY (CrossSellingGuid) REFERENCES CrossSelling(Guid),
CONSTRAINT FK_ProductCrossSelling_ProductGuid FOREIGN KEY (ProductGuid) REFERENCES Product(Guid),
);


CREATE TABLE List
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
Code VARCHAR(200) NULL,
Description VARCHAR(200) NULL,
Value VARCHAR(200) NULL,
CONSTRAINT PK_List_Guid PRIMARY KEY(Guid)
);

CREATE TABLE SupplierItem
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
Code VARCHAR(200) NULL,
Description VARCHAR(200) NULL,
Value VARCHAR(200) NULL,
CONSTRAINT PK_SupplierItem_Guid PRIMARY KEY(Guid)
);

CREATE TABLE SubCategory
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
Code VARCHAR(200) NULL,
Description VARCHAR(200) NULL,
Value VARCHAR(200) NULL,
CONSTRAINT PK_SubCategory_Guid PRIMARY KEY(Guid)
);

CREATE TABLE Vademecum
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
Code VARCHAR(200) NULL,
Description VARCHAR(200) NULL,
Value VARCHAR(200) NULL,
CONSTRAINT PK_Vademecum_Guid PRIMARY KEY(Guid)
);

ALTER TABLE Product ADD VademecumGuid UNIQUEIDENTIFIER NOT NULL;
ALTER TABLE Product ADD CONSTRAINT FK_Product_VademecumGuid FOREIGN KEY (VademecumGuid) REFERENCES Vademecum(Guid);

ALTER TABLE Product ADD SubCategoryGuid UNIQUEIDENTIFIER NOT NULL;
ALTER TABLE Product ADD CONSTRAINT FK_Product_SubCategoryGuid FOREIGN KEY (SubCategoryGuid) REFERENCES SubCategory(Guid);

ALTER TABLE Product ADD ListGuid UNIQUEIDENTIFIER NOT NULL;
ALTER TABLE Product ADD CONSTRAINT FK_Product_ListGuid FOREIGN KEY (ListGuid) REFERENCES List(Guid);

ALTER TABLE Product ADD SupplierItemGuid UNIQUEIDENTIFIER NOT NULL;
ALTER TABLE Product ADD CONSTRAINT FK_Product_SupplierItemGuid FOREIGN KEY (SupplierItemGuid) REFERENCES SupplierItem(Guid);