--------------Tablas Maestras--------------
CREATE TABLE DocumentType
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
Name VARCHAR(200) NOT NULL,
CONSTRAINT PK_DocumentType_Guid PRIMARY KEY(Guid),
);

CREATE TABLE Sex
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
Name VARCHAR(200) NOT NULL,
CONSTRAINT PK_Sex_Guid PRIMARY KEY(Guid),
);

CREATE TABLE Country
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
Name VARCHAR(200) NOT NULL,
CONSTRAINT PK_Country_Guid PRIMARY KEY(Guid),
);

CREATE TABLE City
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
CountryGuid UNIQUEIDENTIFIER NOT NULL,
Name VARCHAR(200) NOT NULL,
CONSTRAINT PK_City_Guid PRIMARY KEY(Guid),
CONSTRAINT FK_City_CountryGuid FOREIGN KEY (CountryGuid) REFERENCES Country(Guid)
);

CREATE TABLE Neighborhood
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
CityGuid UNIQUEIDENTIFIER NOT NULL,
Name VARCHAR(200) NOT NULL,
CONSTRAINT PK_Neighborhood_Guid PRIMARY KEY(Guid),
CONSTRAINT FK_Neighborhood_CityGuid FOREIGN KEY (CityGuid) REFERENCES City(Guid)
);

CREATE TABLE UserRole
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
Name VARCHAR(200) NOT NULL,
CONSTRAINT PK_UserRole_Guid PRIMARY KEY(Guid),
);

CREATE TABLE Category
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
Name VARCHAR(200) NOT NULL,
CONSTRAINT PK_Category_Guid PRIMARY KEY(Guid),
);

CREATE TABLE Kind
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
Name VARCHAR(200) NOT NULL,
CONSTRAINT PK_Kind_Guid PRIMARY KEY(Guid),
);

CREATE TABLE Line
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
Name VARCHAR(200) NOT NULL,
CONSTRAINT PK_Line_Guid PRIMARY KEY(Guid),
);

CREATE TABLE OrderStatus
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
Name VARCHAR(200) NOT NULL,
CONSTRAINT PK_OrderStatus_Guid PRIMARY KEY(Guid),
);


--------------Tablas Principales--------------
CREATE TABLE Phone
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
CountryCode VARCHAR(10) NOT NULL,
CityCode VARCHAR(10) NOT NULL,
PhoneNumber VARCHAR(20) NOT NULL,
CONSTRAINT PK_Phone_Guid PRIMARY KEY(Guid),
);

CREATE TABLE Address
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
CountryGuid UNIQUEIDENTIFIER NOT NULL,
CityGuid UNIQUEIDENTIFIER NOT NULL,
NeighborhoodGuid UNIQUEIDENTIFIER NULL,
Street VARCHAR(200) NOT NULL,
StreetNumber VARCHAR(50) NULL,
PostalCode VARCHAR(20) NOT NULL,
Floor VARCHAR(20) NULL,
Door VARCHAR(20) NULL,
CONSTRAINT PK_Address_Guid PRIMARY KEY(Guid),
CONSTRAINT FK_Address_CountryGuid FOREIGN KEY (CountryGuid) REFERENCES Country(Guid),
CONSTRAINT FK_Address_CityGuid FOREIGN KEY (CityGuid) REFERENCES City(Guid),
CONSTRAINT FK_Address_NeighborhoodGuid FOREIGN KEY (NeighborhoodGuid) REFERENCES Neighborhood(Guid)
);

CREATE TABLE PrincipalImage
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
ImagePath VARCHAR(MAX) NULL,
ImageName VARCHAR(100) NULL,
FullName VARCHAR(100) NULL,
Extension VARCHAR(10) NULL,
CONSTRAINT PK_PrincipalImage_Guid PRIMARY KEY(Guid)
);

CREATE TABLE Product
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
PrincipalImageGuid UNIQUEIDENTIFIER NOT NULL,
Name VARCHAR(200) NOT NULL,
Description VARCHAR(MAX) NOT NULL,
Stock INT NOT NULL,
MinimumStock INT NOT NULL,
UnitPrice DECIMAL NOT NULL,
Brand VARCHAR(100) NULL,
-- TotalPrice DECIMAL NOT NULL,
CONSTRAINT PK_Product_Guid PRIMARY KEY(Guid),
CONSTRAINT FK_Product_PrincipalImageGuid FOREIGN KEY (PrincipalImageGuid) REFERENCES PrincipalImage(Guid)
);

CREATE TABLE GalleryImage
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
ProductGuid UNIQUEIDENTIFIER NOT NULL,
ImagePath VARCHAR(MAX) NULL,
ImageName VARCHAR(100) NULL,
FullName VARCHAR(100) NULL,
Extension VARCHAR(10) NULL,
CONSTRAINT PK_GalleryImage_Guid PRIMARY KEY(Guid),
CONSTRAINT FK_GalleryImage_ProductGuid FOREIGN KEY (ProductGuid) REFERENCES Product(Guid)
);

CREATE TABLE Person
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
DocumentTypeGuid UNIQUEIDENTIFIER NOT NULL,
PhoneGuid UNIQUEIDENTIFIER NOT NULL,
SexGuid UNIQUEIDENTIFIER NOT NULL,
Names VARCHAR(100) NOT NULL,
Surnames VARCHAR(100) NOT NULL,
DateOfBirth DATE NOT NULL,
Age INT NOT NULL,
DocumentNumber VARCHAR(12) NULL,
CONSTRAINT PK_Person_Guid PRIMARY KEY(Guid),
CONSTRAINT FK_Person_DocumentTypeGuid FOREIGN KEY (DocumentTypeGuid) REFERENCES DocumentType(Guid),
CONSTRAINT FK_Person_PhoneGuid FOREIGN KEY (PhoneGuid) REFERENCES Phone(Guid),
CONSTRAINT FK_Person_SexGuid FOREIGN KEY (SexGuid) REFERENCES Sex(Guid)
);

CREATE TABLE AppUser
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
PersonGuid UNIQUEIDENTIFIER NOT NULL,
RoleGuid UNIQUEIDENTIFIER NOT NULL,
Email VARCHAR(100) NOT NULL,
Pass VARCHAR(100) NOT NULL,
Verified BIT NULL,
CONSTRAINT PK_User_Guid PRIMARY KEY(Guid),
CONSTRAINT FK_User_PersonGuid FOREIGN KEY (PersonGuid) REFERENCES Person(Guid),
CONSTRAINT FK_User_RoleGuid FOREIGN KEY (RoleGuid) REFERENCES UserRole(Guid)
);

CREATE TABLE ProductsOrder
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
UserGuid UNIQUEIDENTIFIER NOT NULL,
OrderStatusGuid UNIQUEIDENTIFIER NOT NULL,
TotalPrice DECIMAL NOT NULL,
CONSTRAINT PK_Order_Guid PRIMARY KEY(Guid),
CONSTRAINT FK_Order_UserGuid FOREIGN KEY (UserGuid) REFERENCES AppUser(Guid),
CONSTRAINT FK_Order_OrderStatusGuid FOREIGN KEY (OrderStatusGuid) REFERENCES OrderStatus(Guid)
);


--------------Tablas Intermedias--------------
CREATE TABLE OrderProduct
(
OrderGuid UNIQUEIDENTIFIER NOT NULL,
ProductGuid UNIQUEIDENTIFIER NOT NULL,
Amount INT NOT NULL,
TotalPracieOfProducts DECIMAL NOT NULL,
CONSTRAINT FK_OrderProduct_OrderGuid FOREIGN KEY (OrderGuid) REFERENCES ProductsOrder(Guid),
CONSTRAINT FK_OrderProduct_ProductGuid FOREIGN KEY (ProductGuid) REFERENCES Product(Guid),
);

CREATE TABLE AddressPerson
(
PersonGuid UNIQUEIDENTIFIER NOT NULL,
AddressGuid UNIQUEIDENTIFIER NOT NULL,
CONSTRAINT FK_AddressPerson_PersonGuid FOREIGN KEY (PersonGuid) REFERENCES Person(Guid),
CONSTRAINT FK_AddressPerson_AddressGuid FOREIGN KEY (AddressGuid) REFERENCES Address(Guid),
);

CREATE TABLE ProductCategory
(
ProductGuid UNIQUEIDENTIFIER NOT NULL,
CategoryGuid UNIQUEIDENTIFIER NOT NULL,
CONSTRAINT FK_ProductCategory_ProductGuid FOREIGN KEY (ProductGuid) REFERENCES Product(Guid),
CONSTRAINT FK_ProductCategory_CategoryGuid FOREIGN KEY (CategoryGuid) REFERENCES Category(Guid),
);

CREATE TABLE ProductKind
(
ProductGuid UNIQUEIDENTIFIER NOT NULL,
KindGuid UNIQUEIDENTIFIER NOT NULL,
CONSTRAINT FK_ProductKind_ProductGuid FOREIGN KEY (ProductGuid) REFERENCES Product(Guid),
CONSTRAINT FK_ProductKind_KindGuid FOREIGN KEY (KindGuid) REFERENCES Kind(Guid),
);

CREATE TABLE ProductLine
(
ProductGuid UNIQUEIDENTIFIER NOT NULL,
LineGuid UNIQUEIDENTIFIER NOT NULL,
CONSTRAINT FK_ProductLine_ProductGuid FOREIGN KEY (ProductGuid) REFERENCES Product(Guid),
CONSTRAINT FK_ProductLine_LineGuid FOREIGN KEY (LineGuid) REFERENCES Line(Guid),
);