CREATE TABLE Laboratory
(
Guid UNIQUEIDENTIFIER NOT NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
Name VARCHAR(200) NOT NULL,
CONSTRAINT PK_Laboratory_Guid PRIMARY KEY(Guid),
);