ALTER TABLE Product ADD LaboratoryGuid UNIQUEIDENTIFIER NULL;
ALTER TABLE Product ADD MainComponent VARCHAR(MAX) NULL;
ALTER TABLE Product ADD Drug VARCHAR(MAX) NULL;
ALTER TABLE Product ADD [Action] VARCHAR(MAX) NULL;
ALTER TABLE Product ADD Presentation VARCHAR(MAX) NULL;
ALTER TABLE Product ADD RoutesOfAdministration VARCHAR(MAX) NULL;
ALTER TABLE Product ADD MilkWithdrawal VARCHAR(MAX) NULL;
ALTER TABLE Product ADD MeatRecall VARCHAR(MAX) NULL;
ALTER TABLE Product ADD Discontinued BIT NULL;
ALTER TABLE Product ADD MissingInformation BIT NULL;
ALTER TABLE Product ADD MissingFoto BIT NULL;
ALTER TABLE Product ADD OBS VARCHAR(MAX) NULL;
ALTER TABLE Product ADD CONSTRAINT FK_Product_LaboratoryGuid FOREIGN KEY (LaboratoryGuid) REFERENCES Laboratory(Guid);

ALTER TABLE Product ALTER COLUMN Stock INT NULL;
ALTER TABLE Product ALTER COLUMN MinimumStock INT NULL;
ALTER TABLE Product ALTER COLUMN UnitPrice DECIMAL NULL;
ALTER TABLE Product ALTER COLUMN Description varchar(MAX) NULL;