CREATE TABLE UserProduct
(
Guid UNIQUEIDENTIFIER NOT NULL,
ProductGuid UNIQUEIDENTIFIER NOT NULL,
UserGuid UNIQUEIDENTIFIER NOT NULL,
ProductPrice DECIMAL NULL,
Deleted BIT NOT NULL,
CreatedAt DATE NOT NULL,
UpdatedAt DATE NOT NULL,
CreatedBy UNIQUEIDENTIFIER NOT NULL,
UpdatedBy UNIQUEIDENTIFIER NOT NULL,
CONSTRAINT PK_UserProduct_Guid PRIMARY KEY(Guid),
CONSTRAINT FK_UserProduct_ProductGuid FOREIGN KEY (ProductGuid) REFERENCES Product(Guid),
CONSTRAINT FK_UserProduct_UserGuid FOREIGN KEY (UserGuid) REFERENCES AppUser(Guid),
);